Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$scriptDirectory = Split-Path -Parent $MyInvocation.MyCommand.Path
$addonDirectory = Join-Path $scriptDirectory "addon"
$flashGotPath = Join-Path $addonDirectory "FlashGot.exe"
$xpiPath = Join-Path $scriptDirectory "addon.xpi"
$temporaryRoot = Join-Path $scriptDirectory ".tmp"
$temporaryDirectory = Join-Path $temporaryRoot ([IO.Path]::GetRandomFileName())
$nightlyDirectory = Join-Path $temporaryDirectory "FlashGot-nightly"
$temporaryArchivePath = Join-Path $temporaryDirectory "addon.xpi"
$binaryMetadataPath = Join-Path $addonDirectory "chrome\content\DownloadItBinaryMetadata.sys.mjs"
$generatedMetadataCreated = $false
$nightlyRepository = "benzBrake/Grabby-FlashGot"
$nightlyWorkflow = "nightly.yml"
$nightlyArtifact = "FlashGot-nightly"
$githubApiHeaders = @{
    "Accept" = "application/vnd.github+json"
    "User-Agent" = "DownloadIt-pack"
}
$githubToken = $env:GITHUB_TOKEN
if ([string]::IsNullOrWhiteSpace($githubToken)) {
    $githubToken = $env:GH_TOKEN
}
if (-not [string]::IsNullOrWhiteSpace($githubToken)) {
    $githubApiHeaders["Authorization"] = "Bearer $githubToken"
}
$requiredEntries = @(
    "bootstrap.js"
    "install.rdf"
    "chrome.manifest"
    "FlashGot.exe"
    "chrome/content/DownloadItBinaryMetadata.sys.mjs"
    "chrome/content/DownloadItDownloaders.sys.mjs"
    "chrome/content/DownloadItPanelView.sys.mjs"
    "chrome/content/locales/en-US/downloadit.ftl"
    "chrome/content/locales/zh-CN/downloadit.ftl"
)

try {
    if (-not (Test-Path -LiteralPath $addonDirectory -PathType Container)) {
        throw "Add-on directory does not exist: $addonDirectory"
    }

    New-Item -ItemType Directory -Path $temporaryDirectory -Force | Out-Null

    if (-not (Test-Path -LiteralPath $flashGotPath -PathType Leaf)) {
        Write-Output "[INFO] FlashGot.exe not found locally; downloading the latest nightly build"
        $workflowRunsUri = "https://api.github.com/repos/$nightlyRepository/actions/workflows/$nightlyWorkflow/runs?status=success&per_page=1"
        $workflowRuns = Invoke-RestMethod -Uri $workflowRunsUri -Headers $githubApiHeaders -Method Get
        $latestRun = $workflowRuns.workflow_runs | Select-Object -First 1
        if (-not $latestRun) {
            throw "No successful nightly build was found in $nightlyRepository"
        }

        New-Item -ItemType Directory -Path $nightlyDirectory -Force | Out-Null
        $artifactsUri = "https://api.github.com/repos/$nightlyRepository/actions/runs/$($latestRun.id)/artifacts?per_page=100"
        $artifacts = Invoke-RestMethod -Uri $artifactsUri -Headers $githubApiHeaders -Method Get
        $nightly = $artifacts.artifacts | Where-Object {
            ($_.name -eq $nightlyArtifact) -and (-not $_.expired)
        } | Select-Object -First 1
        if (-not $nightly) {
            throw "The latest successful nightly run has no available $nightlyArtifact artifact"
        }

        $nightlyArchivePath = Join-Path $temporaryDirectory "$nightlyArtifact.zip"
        Invoke-WebRequest -Uri $nightly.archive_download_url -Headers $githubApiHeaders -OutFile $nightlyArchivePath
        Expand-Archive -LiteralPath $nightlyArchivePath -DestinationPath $nightlyDirectory -Force

        $downloadedFlashGotPath = Join-Path $nightlyDirectory "FlashGot.exe"
        if (-not (Test-Path -LiteralPath $downloadedFlashGotPath -PathType Leaf)) {
            throw "The nightly artifact does not contain FlashGot.exe"
        }
        Copy-Item -LiteralPath $downloadedFlashGotPath -Destination $flashGotPath
        Write-Output "[OK] Downloaded $flashGotPath"
    }

    $flashGotFile = Get-Item -LiteralPath $flashGotPath
    $flashGotHash = (Get-FileHash -LiteralPath $flashGotPath -Algorithm SHA256).Hash.ToLowerInvariant()
    Write-Output "[INFO] FlashGot.exe size: $($flashGotFile.Length) bytes"
    Write-Output "[INFO] FlashGot.exe SHA-256: $flashGotHash"

    if (Test-Path -LiteralPath $binaryMetadataPath -PathType Leaf) {
        throw "Generated binary metadata file already exists: $binaryMetadataPath"
    }

    $binaryMetadata = @"
// Generated by pack.ps1. Do not edit this file directly.
export const BINARY_SIZE = $($flashGotFile.Length);
export const BINARY_SHA256 = "$flashGotHash";
"@
    $generatedMetadataCreated = $true
    [IO.File]::WriteAllText(
        $binaryMetadataPath,
        $binaryMetadata,
        [Text.UTF8Encoding]::new($false)
    )

    [IO.Compression.ZipFile]::CreateFromDirectory(
        $addonDirectory,
        $temporaryArchivePath,
        [IO.Compression.CompressionLevel]::Optimal,
        $false
    )

    $archive = [IO.Compression.ZipFile]::OpenRead($temporaryArchivePath)
    try {
        $entryNames = @($archive.Entries | ForEach-Object { $_.FullName })
    }
    finally {
        $archive.Dispose()
    }

    if (-not $entryNames) {
        throw "The generated XPI is empty"
    }
    foreach ($requiredEntry in $requiredEntries) {
        if (-not ($entryNames -contains $requiredEntry)) {
            throw "The generated XPI is missing required entry: $requiredEntry"
        }
    }

    if (Test-Path -LiteralPath $xpiPath -PathType Leaf) {
        [IO.File]::Move($temporaryArchivePath, $xpiPath, $true)
    }
    else {
        [IO.File]::Move($temporaryArchivePath, $xpiPath)
    }
    Write-Output "[OK] Created $xpiPath"
}
catch {
    Write-Error "Failed to package DownloadIt: $_"
    exit 1
}
finally {
    if ($generatedMetadataCreated -and (Test-Path -LiteralPath $binaryMetadataPath -PathType Leaf)) {
        Remove-Item -LiteralPath $binaryMetadataPath -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $temporaryDirectory) {
        Remove-Item -LiteralPath $temporaryDirectory -Recurse -Force -ErrorAction SilentlyContinue
    }
}
